# Generated by Django 4.1.7 on 2023-03-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_post_post_date_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Welcome to my profile!'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x10b881350> <django.db.models.query_utils.DeferredAttribute object at 0x10b881390>', max_length=200),
        ),
    ]
