# Generated by Django 4.1.7 on 2023-03-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_profile_bio_profile_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='header',
            field=models.ImageField(default='default_header.jpg', upload_to='header_pics'),
        ),
    ]
