# Generated by Django 4.1.7 on 2023-03-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Welcome to my profile!', max_length=160),
        ),
    ]
