# Generated by Django 4.1.7 on 2023-03-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commenter',
        ),
    ]
