# Generated by Django 4.1.7 on 2023-03-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='header',
        ),
    ]
