# Generated by Django 4.1.7 on 2023-03-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_remove_profile_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
